{% set name = "flux-pmix" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-pmix/releases/download/v{{ version }}/flux-pmix-{{ version }}.tar.gz
  sha256: 31f9d9b99f8a75c05e2fd183a35998f104d8e80bd819c57252aca477be0d4c6e
  patches:
    - test.patch

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
  host:
    - flux-core
    - {{ mpi }}
    - jansson
    - libpmix
    - libpmix-devel
  run:
    - flux-core
    - {{ mpi }}

test:
  commands:
    - flux --help

about:
  home: https://github.com/flux-framework/flux-pmix
  summary: 'flux shell plugin to bootstrap openmpi v5+'
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
