{% set name = "flux-pmix" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-pmix/releases/download/v{{ version }}/flux-pmix-{{ version }}.tar.gz
  sha256: f382800b1a342df0268146ea7ce33011299bf0c69a46ac8a52e87de6026c9322
  patches:
    - test.patch  # disable tests which require multiple compute nodes

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - flux-core
    - openmpi >5.0
    - jansson
  run:
    - flux-core
    - openmpi >5.0

test:
  commands:
    - flux --help

about:
  home: https://github.com/flux-framework/flux-pmix
  summary: 'flux shell plugin to bootstrap openmpi v5+'
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
